(ns gen
  "Rebuild the files that list every demo (`bb gen`).

  demos.edn is the list, edited by hand. From it and the demo directories this
  writes:

  - deps.edn                                      one alias per demo, plus :check
  - <demo>/deps.edn and <demo>/bb.edn             each demo's project files
  - src/net/b12n/raylib_clj_demo/check.clj        requires every scene namespace
  - bb.edn, between its BEGIN/END markers         one task per demo
  - docs/guide/demos.md                           the site's gallery

  Each demo's source, its docs page, its resources and its recordings are
  hand-owned. gen only reads them.

  Usage: bb gen [--check]
  --check writes nothing and exits 1 if any of those files is out of date."
  (:require
   [babashka.fs :as fs]
   [clojure.edn :as edn]
   [clojure.string :as str]))

(def root (str (fs/parent (fs/parent (fs/absolutize *file*)))))

(def ns-prefix "net.b12n.raylib-clj.scenes.")

(def repo-url "https://github.com/b12n-oss/raylib-clj-demo")

(def jvm-opts ["--enable-native-access=ALL-UNNAMED"])

;; The hand-written tasks in bb.edn. A demo with one of these names gets no task
;; of its own, though `bb run <demo>` still reaches it.
(def fixed-tasks #{"info" "list" "run" "run-all" "check" "lint" "lint:strict" "doctor" "gen"
                   "record" "sync-recordings" "demos:examples"})

(def begin-marker "  ;; BEGIN per-demo tasks, generated by `bb gen`\n")
(def end-marker "  ;; END per-demo tasks\n")

(defn- ->file [name] (str (str/replace name "-" "_") ".clj"))

(defn- demo-dirs
  "Every directory here holding a demo: a deps.edn and its scene source."
  []
  (sort (for [d (fs/list-dir root)
              :let [name (str (fs/file-name d))]
              :when (and (fs/exists? (fs/file d "deps.edn"))
                         (fs/exists? (fs/file d "src/net/b12n/raylib_clj/scenes" (->file name))))]
          name)))

(defn- media-of
  "The demo's recording under docs/demos, gif preferred, or nil."
  [name]
  (first (for [ext ["gif" "png"]
               :when (fs/exists? (fs/file root "docs/demos" (str name "." ext)))]
           (str name "." ext))))

(defn- edn-vec [xs] (str "[" (str/join " " (map pr-str xs)) "]"))

(defn- root-deps-edn [entries]
  (let [w (inc (apply max (map (comp count :name) entries)))
        pad (fn [s] (format (str "%-" w "s") s))
        demo-deps (str/join "\n" (for [{n :name} entries]
                                   (str "        net.b12n.raylib-clj-demo/" n " {:local/root \"" n "\"}")))
        aliases (str/join "\n" (for [{n :name} entries]
                                 (str "  " (pad (str ":" n))
                                      " {:main-opts [\"-m\" \"" ns-prefix n "\"]}")))]
    (str ";; Root of raylib-clj-demo. Every demo is its own sub-project (<demo>/deps.edn)\n"
         ";; and runs from its own directory with `bb run`, which is where its\n"
         ";; resources/ resolve. On the JVM, run `clojure -M:jvm:<demo>` from here,\n"
         ";; adding :mac on macOS, for a demo that loads no files from resources/.\n"
         ";;\n"
         ";; Generated by `bb gen` from demos.edn. Don't hand-edit the aliases: add the\n"
         ";; demo to demos.edn and re-run it instead. The bindings arrive through\n"
         ";; common/, which depends on the repository root.\n"
         "{:paths [\"src\"]\n"
         " :deps {net.b12n/raylib-clj-demo-common {:local/root \"common\"}\n"
         demo-deps "}\n"
         " :aliases\n"
         " {:jvm {:jvm-opts " (edn-vec jvm-opts) "}\n"
         "  :mac {:jvm-opts [\"-XstartOnFirstThread\"]}\n"
         "  :check {:main-opts [\"-m\" \"net.b12n.raylib-clj-demo.check\"]}\n"
         "\n"
         aliases "}}\n")))

(defn- demo-deps-edn [name]
  (str "{:paths [\"src\"]\n"
       " :deps {net.b12n/raylib-clj-demo-common {:local/root \"../common\"}}\n"
       " :aliases {:run {:jvm-opts " (edn-vec jvm-opts) "\n"
       "                 :main-opts [\"-m\" \"" ns-prefix name "\"]}\n"
       "           :mac {:jvm-opts [\"-XstartOnFirstThread\"]}}}\n"))

(defn- demo-bb-edn [{:keys [name desc]}]
  (str ";; Run this demo from here with `bb run`. From the repo root it's\n"
       ";; `bb " name "`. Generated by `bb gen`.\n"
       "{:deps {net.b12n.raylib-clj-demo/" name " {:local/root \".\"}}\n"
       " :tasks\n"
       " {run {:doc " (pr-str (str "\u25b6 " (or desc name))) "\n"
       "       :override-builtin true\n"
       "       :requires ([" ns-prefix name "])\n"
       "       :task (apply " ns-prefix name "/-main *command-line-args*)}}}\n"))

(defn- check-clj [entries]
  (str "(ns net.b12n.raylib-clj-demo.check\n"
       "  \"Headless compile-check (`bb check` from the repo root).\n"
       "\n"
       "  Requires every scene namespace, which compiles each one and links the\n"
       "  library against libraylib, WITHOUT opening a window: no -main is called.\"\n"
       "  (:require\n"
       (str/join "\n" (for [{n :name} entries] (str "   [" ns-prefix n "]")))
       "))\n"
       "\n"
       "(defn -main [& _]\n"
       "  (println \"OK: every scene namespace compiled\")\n"
       "  (shutdown-agents))\n"))

(defn- bb-edn-with-tasks
  "bb.edn's text with the block between the markers replaced, or nil when the
  markers are missing."
  [text entries]
  (let [b (str/index-of text begin-marker)
        e (some-> b (->> (str/index-of text end-marker)))]
    (when (and b e)
      (let [named (remove (comp fixed-tasks :name) entries)
            w (apply max (map (comp count :name) named))]
        (str (subs text 0 (+ b (count begin-marker)))
             (str/join (for [{:keys [name desc]} named]
                         (str "  " (format (str "%-" w "s") name)
                              " {:doc " (pr-str (str "▶ " (or desc name)))
                              " :task (exit-with (run-demo " (pr-str name) "))}\n")))
             (subs text e))))))

(defn- gallery-md [entries]
  (str "<!-- Generated by `bb gen` from demos.edn. Edits here are overwritten. -->\n"
       "# Demo gallery\n"
       "\n"
       "All " (count entries) " demos, grouped by category. Each name links to the demo's\n"
       "own sub-project, where its page has the full description and source.\n"
       (str/join
        (for [[category ds] (sort-by key (group-by (fn [e] (or (:category e) "local")) entries))]
          (str "\n## " category " (" (count ds) ")\n"
               (str/join
                (for [{:keys [name title desc controls]} ds]
                  (str "\n### [" (or title name) "](" repo-url "/tree/main/" name ")\n\n"
                       (when desc (str desc ". "))
                       (when controls (str "Controls: " controls ". "))
                       "Run it with `bb " (if (fixed-tasks name) (str "run " name) name) "`.\n\n"
                       (when-let [m (media-of name)] (str "![" name "](../demos/" m ")\n"))))))))))

(defn- fail! [& msg]
  (binding [*out* *err*] (println (apply str msg)))
  (System/exit 1))

(defn -main [& args]
  (let [check? (some #{"--check"} args)
        entries (sort-by :name (edn/read-string (slurp (fs/file root "demos.edn"))))
        listed (set (map :name entries))
        on-disk (set (demo-dirs))
        bb-edn (fs/file root "bb.edn")
        bb-text (bb-edn-with-tasks (slurp bb-edn) entries)
        outputs [[(fs/file root "deps.edn") (root-deps-edn entries)]
                 [(fs/file root "src/net/b12n/raylib_clj_demo/check.clj") (check-clj entries)]
                 [bb-edn bb-text]
                 [(fs/file root "docs/guide/demos.md") (gallery-md entries)]]
        outputs (into outputs
                      (mapcat (fn [{n :name :as e}]
                                [[(fs/file root n "deps.edn") (demo-deps-edn n)]
                                 [(fs/file root n "bb.edn") (demo-bb-edn e)]]))
                      entries)]
    (when-let [missing (seq (sort (remove on-disk listed)))]
      (fail! "In demos.edn with no demo directory: " (str/join " " missing)))
    (when-let [unlisted (seq (sort (remove listed on-disk)))]
      (fail! "Demo directories missing from demos.edn: " (str/join " " unlisted)))
    (when-not bb-text
      (fail! "bb.edn has lost its BEGIN/END per-demo task markers"))
    (when-let [clash (seq (filter fixed-tasks listed))]
      (println "No task of their own (name taken by a bb.edn task):" (str/join " " clash)))
    (let [stale (for [[f content] outputs
                      :when (not= content (when (fs/exists? f) (slurp f)))]
                  [f content])]
      (doseq [[f content] stale]
        (println (if check? "out of date:" "updated:") (str (fs/relativize root f)))
        (when-not check?
          (fs/create-dirs (fs/parent f))
          (spit f content)))
      (println (str (count entries) " demos, " (count stale) " file(s) "
                    (if check? "out of date" "changed")))
      (when (and check? (seq stale))
        (fail! "Run `bb gen` and commit the result.")))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
