(ns raylib.check
  "Loads every namespace of the library without opening a window.
  Run with: bb check"
  (:require
   [raylib-clj.audio]
   [raylib-clj.colors]
   [raylib-clj.core]
   [raylib-clj.core.camera2d]
   [raylib-clj.core.camera3d]
   [raylib-clj.core.collision]
   [raylib-clj.core.cursor]
   [raylib-clj.core.drawing]
   [raylib-clj.core.gamepad]
   [raylib-clj.core.gestures]
   [raylib-clj.core.keyboard]
   [raylib-clj.core.mouse]
   [raylib-clj.core.shaders]
   [raylib-clj.core.timing]
   [raylib-clj.core.window]
   [raylib-clj.debug-stats]
   [raylib-clj.easings]
   [raylib-clj.enums]
   [raylib-clj.lights]
   [raylib-clj.models]
   [raylib-clj.nrepl]
   [raylib-clj.raygui]
   [raylib-clj.raymath]
   [raylib-clj.shapes.basic]
   [raylib-clj.structs]
   [raylib-clj.text.drawing]
   [raylib-clj.textures.drawing]
   [raylib-clj.textures.texture-loading]
   [raylib-clj.utils]
   [raylib.all]
   [raylib.audio]
   [raylib.camera]
   [raylib.color]
   [raylib.core]
   [raylib.files]
   [raylib.images]
   [raylib.input]
   [raylib.kwargs]
   [raylib.log]
   [raylib.models]
   [raylib.native]
   [raylib.rays]
   [raylib.repl]
   [raylib.rlgl]
   [raylib.shaders]
   [raylib.shapes]
   [raylib.splines]
   [raylib.text]
   [raylib.textures]
   [raylib.util]))

(defn -main [& _]
  (println "All namespaces loaded."))
