(ns gen-all
  "Writes src/raylib/all.clj, which re-exports the public vars of every module.
  Run with: bb gen:all"
  (:require [clojure.string :as str]))

(def modules
  '[audio camera color core files images input kwargs log models native
    rays repl rlgl shaders shapes splines text textures util])

(def excluded '#{-main})

(defn publics [module]
  (let [ns-sym (symbol (str "raylib." module))]
    (require ns-sym)
    (->> (ns-publics ns-sym)
         keys
         (remove excluded)
         sort)))

(defn generate []
  (let [by-module (into (sorted-map) (map (juxt identity publics)) modules)
        names (mapcat val by-module)
        dupes (->> names frequencies (filter #(> (val %) 1)) (map key))
        shadowed (sort (filter (ns-publics 'clojure.core) names))]
    (when (seq dupes)
      (throw (ex-info (str "Duplicate public names: " (str/join " " dupes)) {})))
    (str ";; Generated by script/gen_all.clj. Do not edit. Run bb gen:all.\n"
         "(ns raylib.all\n"
         "  \"Re-exports the public vars of every raylib module.\"\n"
         (format "  (:refer-clojure :exclude [%s])\n" (str/join " " shadowed))
         "  (:require\n"
         (str/join "\n" (for [m modules] (str "   [raylib." m " :as " m "]")))
         "))\n"
         (str/join
          (for [[m syms] by-module
                s syms]
            (format "\n(def %s %s/%s)\n(alter-meta! #'%s merge (select-keys (meta #'%s/%s) [:doc :arglists :const]))"
                    s m s s m s)))
         "\n")))

(defn -main [& _]
  (spit "src/raylib/all.clj" (generate)))
